-- Stores each manual cloud sync so the dashboard can replay versions from today.
-- Apply after enabling Supabase Auth; ticket data is available only to signed-in users.

create table if not exists public.app_snapshots (
    id bigint generated by default as identity primary key,
    captured_at timestamptz not null default now(),
    csv_modified_at timestamptz,
    tickets jsonb not null
);

alter table public.app_snapshots
    add column if not exists csv_modified_at timestamptz;

create index if not exists app_snapshots_captured_at_idx
    on public.app_snapshots (captured_at);

alter table public.app_snapshots enable row level security;

revoke all on table public.app_snapshots from public, anon;
grant select, insert on table public.app_snapshots to authenticated;
revoke all on sequence public.app_snapshots_id_seq from public, anon;
grant usage, select on sequence public.app_snapshots_id_seq to authenticated;

drop policy if exists app_snapshots_anon_select on public.app_snapshots;
drop policy if exists app_snapshots_authenticated_select on public.app_snapshots;
create policy app_snapshots_authenticated_select
    on public.app_snapshots for select to authenticated
    using ((auth.jwt() -> 'app_metadata' ->> 'service_number') ~ '^[0-9]{6}$');

drop policy if exists app_snapshots_anon_insert on public.app_snapshots;
drop policy if exists app_snapshots_authenticated_insert on public.app_snapshots;
create policy app_snapshots_authenticated_insert
    on public.app_snapshots for insert to authenticated
    with check ((auth.jwt() -> 'app_metadata' ->> 'service_number') ~ '^[0-9]{6}$');

-- Restrict the current ticket set to authenticated dashboard users as well.
alter table public.app_state enable row level security;
revoke all on table public.app_state from public, anon;
grant select, insert, update on table public.app_state to authenticated;

drop policy if exists app_state_authenticated_select on public.app_state;
create policy app_state_authenticated_select
    on public.app_state for select to authenticated
    using ((auth.jwt() -> 'app_metadata' ->> 'service_number') ~ '^[0-9]{6}$');

drop policy if exists app_state_authenticated_insert on public.app_state;
create policy app_state_authenticated_insert
    on public.app_state for insert to authenticated
    with check (id = 1 and (auth.jwt() -> 'app_metadata' ->> 'service_number') ~ '^[0-9]{6}$');

drop policy if exists app_state_authenticated_update on public.app_state;
create policy app_state_authenticated_update
    on public.app_state for update to authenticated
    using (id = 1 and (auth.jwt() -> 'app_metadata' ->> 'service_number') ~ '^[0-9]{6}$')
    with check (id = 1 and (auth.jwt() -> 'app_metadata' ->> 'service_number') ~ '^[0-9]{6}$');

notify pgrst, 'reload schema';